export const enum ClickAction {
    nav,
    subnav,
    contact,
    product_show,
    product_turn,
    product_next,
    product_info,
    product_share,
    product_gallery,
    product_order,
    lower_lift,
    filter,
    story_nav,
    slider,
}
